#!/bin/bash

set -ex

function write_key() {
    mkdir -p "${JENKINS_HOME}/.ssh"
    echo "$1" > "${JENKINS_HOME}/.ssh/authorized_keys"
    chown -Rf ${JENKINS_USER}:${JENKINS_GROUP} "${JENKINS_HOME}/.ssh"
    chmod 0700 "${JENKINS_HOME}/.ssh"
    chmod 0600 "${JENKINS_HOME}/.ssh/authorized_keys"
}

if [[ $JENKINS_SLAVE_SSH_PUBKEY == ssh-* ]]; then
    write_key "${JENKINS_SLAVE_SSH_PUBKEY}"
fi

if [[ $# -gt 0 ]]; then
    if [[ $1 == ssh-* ]]; then
        write_key "$1"
        shift 1
    else
        exec "$@"
    fi
fi

# ensure variables passed to docker container are also exposed to ssh sessions
env | grep _ >> /etc/environment

ssh-keygen -A
exec /usr/sbin/sshd -D -e "${@}"
